print("Biodata Diri")
Nama_Lengkap = input("Masukan Nama Lengkap: ")
Tempat_Lahir =input("Masukan Tempat Lahir: ")
Tanggal_Lahir =int(input("Masukan Tanggal Lahir: "))
Asal_Sekolah = input("Masukan Asal Sekolah: ")
Usia =int(input("Masukan Usia: ")) 
Tinggi_Badan =float(input("Masukan Tinggi Badan:"))
Berat_Badan = float(input("Masukan Berat Badan:"))
Sudah_Cukup_Umur = (input().lower() == 'true')

print ("Biodata Diri")
print ("========================================================")
print (f" {'Nama_Lengkap'} : {Nama_Lengkap}")
print (f" {'Tempat_Lahir'} : {Tempat_Lahir:}" )
print (f" {'Tanggal_Lahir'} : {Tanggal_Lahir}")
print (f" {'Asal Sekolah'} : {Asal_Sekolah} ")
print (f" {'Usia'} : {Usia}")
print (f" {'Tinggi Badan'} : {Tinggi_Badan}")
print (f" {'Berat Badan'} : {Berat_Badan}")
print ("Sudah Cukup Umur : " + str(Sudah_Cukup_Umur))
print ("=========================================================")